//auth
export const SET_APP_USER = "SET_APP_USER"
export const USER_LOGOUT = "USER_LOGOUT"
export const SET_AUTH_LOADING = "SET_AUTH_LOADING"
export const SIGN_UP = "SIGNUP_SUCCESS"
export const FCM_TOKEN = "FCM_TOKEN"

export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const GETUSER_SUCCESS = "GETUSER_SUCCESS"
export const SET_PROFILE = "SET_PROFILE"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const IMAGE_DATA = "IMAGE_DATA"
export const PROFILE_COMPLETE = "PROFILE_COMPLETE"
export const PROFILE_STATUS = "PROFILE_STATUS"
export const PROFILE_SPORT_SELC = "PROFILE_SPORT_SELC"
export const MANAGE_PROFILE_UPDATED = "MANAGE_PROFILE_UPDATED"
export const PROFILE_UPDATED = "PROFILE_UPDATED"
export const GET_USER_PROFILES = "GET_USER_PROFILES"

export const MY_PROFILE_STATUS = {
    COMPLETE_PROFILE : "COMPLETE_PROFILE",
    JOIN_TEAM : "JOIN_TEAM"
}

export const MY_SPORT_SELECTION = {
    SPORT_SELECTED : "SPORT_SELECTED"
}

//utils
// export const SHOW_LOADER = "SHOW_LOADER"

// 